services:
  mediaclipmakarr:
    build: .
    ports:
      - "3623:8000"
    environment:
      MCM_SOURCE_DIRS: '["/media"]'
    volumes:
      - private-data:/data/private
      - work-data:/data/work
      - clip-library:/data/clips
      - ./data/sources:/media:ro
    restart: unless-stopped

volumes:
  private-data:
  work-data:
  clip-library:
